---
abstract: A data structure optimized for prefix lookup.
author: 'Copyright 2007 Avi Finkel <F<avi@finkel.org>>'
build_requires:
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Tree-Trie
no_index:
  directory:
    - inc
    - t
version: 1.4
